services:
  sts:
    build: .
    container_name: sts-solver
    volumes:
      - type: bind
        source: ./res
        target: /app/res
      - type: bind
        source: ./test
        target: /app/test
      - type: bind
        source: ./source
        target: /app/source
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    command: /bin/bash
