name: Quick STS Test

on:
  # Manual trigger for quick testing
  workflow_dispatch:
    inputs:
      team_numbers:
        description: 'Team numbers to test (comma-separated)'
        required: false
        default: '2,4'
      model:
        description: 'Single model to run'
        required: false
        default: 'SAT'
        type: choice
        options:
          - CP
          - MIP
          - SAT
          - SMT
      timeout:
        description: 'Timeout in seconds'
        required: false
        default: '120'

jobs:
  quick-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies (minimal)
      run: |
        python -m pip install --upgrade pip
        # Install only essential dependencies for quick test
        pip install z3-solver python-sat pulp matplotlib
        
    - name: Quick model test
      run: |
        cd test
        
        # Parse team numbers
        TEAM_NUMBERS=$(echo "${{ github.event.inputs.team_numbers }}" | tr ',' ' ')
        
        echo "Running quick test: ${{ github.event.inputs.model }} model"
        echo "Team numbers: $TEAM_NUMBERS"
        
        python run_all_models.py \
          --models ${{ github.event.inputs.model }} \
          --n-values $TEAM_NUMBERS \
          --mode generate \
          --timeout ${{ github.event.inputs.timeout }} \
          --verbose
        
    - name: Show results
      if: always()
      run: |
        echo "## Quick Test Results" >> $GITHUB_STEP_SUMMARY
        echo "**Model:** ${{ github.event.inputs.model }}" >> $GITHUB_STEP_SUMMARY
        echo "**Team Numbers:** ${{ github.event.inputs.team_numbers }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        # Check for new result files
        if find res -name "*.json" -newer requirements.txt 2>/dev/null | head -5; then
          echo "✅ Test completed successfully - new results generated" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ Test may have failed - no new results detected" >> $GITHUB_STEP_SUMMARY
        fi
